### ISSUE TITLE
Industrial miner causes crash when used in conjunction with minecart mod.

### ISSUE THREAD

**Issue by zeners** [theFox6/factory#15]
The industrial miner crash when starting to work, if the [minecart](https://content.minetest.net/packages/joe7575/minecart/) mod is loaded.
`2020-09-24 19:00:03: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'factory' in callback LuaABM::trigger(): Invalid position (expected table got nil).
2020-09-24 19:00:03: ERROR[Main]: stack traceback:
2020-09-24 19:00:03: ERROR[Main]: 	[C]: in function 'get_node'
2020-09-24 19:00:03: ERROR[Main]: 	/home/user/.minetest/mods/minecart/protection.lua:45: in function 'is_protected'
2020-09-24 19:00:03: ERROR[Main]: 	/home/user/.minetest/mods/factory/machines/miner.lua:88: in function </home/user/.minetest/mods/factory/machines/miner.lua:78>`

I don't know, which of the two should/could fix it.
https://github.com/joe7575/minecart/issues/4#issue-708349506

**Comment by joe7575** [comment]
I assume it comes from the miner. It does not provide a valid 'pos': `...Invalid position (expected table got nil)...`.
But independent on that I will add a check so that the crash will not happen inside my mod :)

**Comment by joe7575** [comment]
@zeners It looks like, you are not using the latest version of the mod factory (there is no call `minetest.is_protected` in line 88)

**Comment by theFox6** [comment]
This bug was fixed in #7 .
To solve the problem try updating your copy of the factory mod.

**Comment by zeners** [comment]
You are absolutly right. great thanks for the very quick response. I was on the wrong repository. Sorry
