### ISSUE TITLE
Starting Miner machine caused mt to exit with error

### ISSUE THREAD

**Issue by Alatarius** [theFox6/factory#20]
**Describe the bug**
Starting Miner machine caused minetest to exit with error

**To Reproduce**
If known, steps to reproduce the behavior:
1. Place miner
2. See error

**Expected behavior**
The the miner would do its thing and mine

**Screenshots**

**Log**
from error screen on exit:
AsyncErr: Lua: Runtime error from mod 'factory' in callback LuaABM::trigger(): D:\Games\Minetest\bin\..\mods\factory/machines/miner.lua:253: attempt to index local 'registered' (a nil value)
stack traceback:
	D:\Games\Minetest\bin\..\mods\factory/machines/miner.lua:253: in function <D:\Games\Minetest\bin\..\mods\factory/machines/miner.lua:228>

from debug.txt:
 2023-11-24 13:11:37: ERROR[Main]: stack traceback:
2023-11-24 13:11:37: ERROR[Main]: 	D:\Games\Minetest\bin\..\mods\factory/machines/miner.lua:253: in function <D:\Games\Minetest\bin\..\mods\factory/machines/miner.lua:228>
2023-11-24 13:11:37: ACTION[Server]: [doc] Wrote player data into D:\Games\Minetest\bin\..\worlds\Mining Town/doc.mt.
2023-11-24 13:11:37: ACTION[Server]: singleplayer leaves game. List of players: 
2023-11-24 13:11:38: ACTION[Main]: Server: Shutting down
2023-11-24 13:11:38: ACTION[Main]: [doc] Server shuts down. Player data is about to be saved.
2023-11-24 13:11:38: ACTION[Main]: [doc] Wrote player data into D:\Games\Minetest\bin\..\worlds\Mining Town/doc.mt.
2023-11-24 13:11:38: ACTION[Main]: [Tubelib] Store data...
2023-11-24 13:11:38: ACTION[Main]: [Tubelib] Data stored. t=297us

**Desktop (please complete the following information):**
 - Minetest version: 5.7.0
 - Other mods activated:
3d_apple, 3d_armor, ambience, amethyst_new, animalworld, anvil, area_containers, artdeco, auroras, awards, bakedclay, banner, basic_materials, beds, biofuel, biomeinfo, biome_lib, bonemeal, bows, bricks_plus, bucket, bucket_wooden, builtin_item, carpets, castle_farming, castle_gates, castle_lighting, castle_masonry, castle_shields, castle_storage, castle_tapestries, castle_weapons, connected_chests, controls, cottages, cracked_castle, craftguide, darkage, decorations_sea, deepslate, diggicontrol, digilines, digistuff, digtron, display_modpack, doc, doc_basics, doc_encyclopedia, doc_identifier, doc_items, doors, drinks, ebiomes, ethereal, etherium_stuff, everness, factory_bridges, farming, flowerpot, geodes_lib, glass_stained, handle_schematics, hangglider, hopper, illumination, itemframes, item_drop, leads, leather_armor, livingcaves, livingcavesmobs, livingdesert, livingfloatlands, livingjungle, livingnether, loot, lwcomponents, lwscratch, marinara, marinaramobs, mesecons, mesecons_carts, mesecons_x, micupack, minecart, mobkit, mobs, mobs_monster, mobs_skeletons, mobs_sky, mobs_water, mob_horse, modlib, modname_tooltip, modutil, moreblocks, moredecorations, morelights, moreores, moretorches, moretrees, music_modpack, nativevillages, naturalbiomes, nether, new_campfire, obsidianstuff, paintings_gallery, paintings_lib, pipeworks, pipunhole, plantlife_modpack, plaster, powerbanks, redef, regrowing_fruits, rnd, ropes, scaffolding, servercleaner, shallow_ores, signs_lib, simple_furniture, skinsdb, slats, stackslabs, stainedglass, stripped_tree, sugar, swamp, technic_plus, technic_recipes, techpack, tga_encoder, torch_bomb, tpad, ts_furniture, tt, tubelib2, unifieddyes, unified_inventory, variety, visible_sneak, void_chest, we_undo, wilhelminessounds, wine, woodcutting, worldedit, worldedit_hud_helper, xdecor, xmaps, x_enchanting, x_farming, factory

**Comment by theFox6** [comment]
This seems to have been caused by unregistered blocks. Which can pop up if mods are removed.
The latest release (v3.4.2) should fix the crash and stop the miner instead.
