### ISSUE TITLE
No craft for sapling treatment plant

### ISSUE THREAD

**Issue by WoosterUK** [theFox6/factory#9]
machines/crafting.lua should contain a recipe for factory:stp; it doesn't currently.

**Comment by theFox6** [comment]
The sapling treatment plant is kind of cheating in my opinion, also the drops are not accurate. If you want me to create a recipe - even if it might overrun some balancing - it would be pretty expensive... (something with diamond gears or mese)
You are welcome to suggest some recipe components or just tell me if I should think of something myself.

**Comment by WoosterUK** [comment]
I guess the point is that it's documented but not actually made available in-game, and also that the sapling fertiliser *does* have a recipe but no use. So it currently feels like a half-feature, and to me at least, it gives the whole mod a feeling of being in a very unfinished, even abandoned, state.

Maybe I'd suggest something like the following:

{
	{ "factory:factory_brick", "default:dirt", "factory:factory_brick" },
	{ "factory:factory_brick", "factory:small_diamond_gear", "factory:factory_brick" },
	{ "factory:factory_brick", "factory:sapling_fertilizer", "factory:factory_brick" }
}

I'd also suggest, if you're worried about balance (which could well be legitimate), that you make fertiliser more expensive. One thing to do would be to make the recipe:

{
	{ "default:leaves", "default:leaves", "default:leaves" },
	{ "default:leaves", "default:dirt", "default:leaves" },
	{ "default:leaves", "default:leaves", "default:leaves" }
}

which would force the player to gather leaves from actual trees every now and again, instead of magicking up wood all the time.

**Comment by theFox6** [comment]
I added a craft recipe in 5cf8bd1
